pipeline {
    agent none
      environment {
        registry = "davout123/py"
        registryCredential = "docker_creds"
        dockerImage = ''
      }
    stages {
        stage('wtf') {
            agent any
             steps {
                script {
                    sh 'ls -a'
                    sh 'docker container ls -a'
                    sh 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'
                }
             }

         }
         stage('Deploy') {
            agent any
             steps {
                script {
                    dockerImage = docker.build(registry)
                      docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                      }
                }
             }

         }

        stage('Remote SSH') {
            agent any
            steps {
                sshagent(['pi_key']) {
                    sh 'ssh -o StrictHostKeyChecking=no pi@192.168.1.12 "bash -x deploy.sh"'
                }
            }
        }




    }
}


